"""Add Stand model

Revision ID: 4427407eb8d2
Revises: d7f90e717bb7
Create Date: 2026-05-17 15:32:01.874898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4427407eb8d2'
down_revision: Union[str, Sequence[str], None] = 'd7f90e717bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pin_code', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stands_id'), 'stands', ['id'], unique=False)
    op.create_index(op.f('ix_stands_pin_code'), 'stands', ['pin_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stands_pin_code'), table_name='stands')
    op.drop_index(op.f('ix_stands_id'), table_name='stands')
    op.drop_table('stands')
    # ### end Alembic commands ###
